### ISSUE TITLE
能否制作一个从安装到实现的完整视频？

### ISSUE THREAD

**Issue by caviar-cn** [butaixianran/Blender-Vmd-Retargeting#11]
为了解决某些VMD动画转G8失败的问题， 我又一次尝试了安装 Blender2.7 到 Blender3.1 的几个 版本，仍然无法实现转身，
能否制作一个完整的，从安装 VmdRetargeting 导出 G8模型，到实现转换的完整视频？
这样我可以按照视频上的软件版本和参数，进行再一次尝试。
感谢。

**Comment by butaixianran** [comment]
反复安装blender没有用，如果缺少3D基础知识和Blender基础，请不要盲目按照自己的猜测去尝试，老老实实按照使用说明的文档，一步不改动的操作即可。


另外，你之前不是尝试了DTB吗，DTB只要安装成功，使用时就是不会有问题的。请按照我们给你的回复，把DTB安装正确，就不会有人模导出和导入时的设置问题了

**Comment by butaixianran** [comment]
视频教程：
https://youtu.be/li7yjJKbbgI
有中文字幕

b站：
https://www.bilibili.com/video/BV1eu411q7qp/
