### ISSUE TITLE
我又回来了，依然对无法转身的问题不死心。

### ISSUE THREAD

**Issue by caviar-cn** [butaixianran/Blender-Vmd-Retargeting#12]
【动作配布】《月夜》
https://www.aplaybox.com/details/motion/ECHzvzpWfU1T
下载地址
无法转身，
我仔细分析了下，发现 月夜 的骨骼和标准骨骼有很多差异如图:
![image](https://user-images.githubusercontent.com/101509220/163861604-3ff4d4c7-430f-49a3-adf5-507d58587ce8.png)
月夜这个动作配布，用的骨骼多一个，
![image](https://user-images.githubusercontent.com/101509220/163861739-79700faf-5e74-4b74-be2a-afc7f128f970.png)
上图是mmd标准骨骼， 只有一个
就因为 月夜 动作配布 里骨骼多的那一个，导致动作转换无法转身，其他地方还有几处不同，您分析下这个的吧。

现在大多动作配布，如果是手K的，基本都是骨骼数比较多的，也大多无法转身，并且转化的时候出现肢体跳动的现象。

上面的 月夜 动作配布 只是其中一个，我近期下载很多动作配布，感觉只有1/4的能正常转换，能正常转换的配布多半是动补软件转换的，手k的动作十有八九就不能转换。

**Comment by caviar-cn** [comment]
补充上图中 骨骼较多的模型下载地址:
TDA TinyChina Miku
https://www.aplaybox.com/details/model/noo6GyHEr4mG

**Comment by butaixianran** [comment]
hi, 已经说过了不是mmd模型问题。你一直在盲人摸象一样尝试，而且尝试的方向完全不对，这样是解决不了问题的。

在blender中，加载vmd文件时，不会读取任何mmd模型，去研究mmd模型并没有用处。

你以前提供的截图已经显示，是你的Daz模型，没有正确导入Blender。

你要的全流程视频教程，也给提供了，请先确认你设置等操作，符合视频教程：
[https://www.bilibili.com/video/BV1eu411q7qp/](https://www.bilibili.com/video/BV1eu411q7qp/)  

上次也跟你提到了，只要正确安装DTB，就不会有Daz模型导入Blender时设置不正确的问题。你可以继续尝试DTB。

你这次提供的vmd动作，也是可以很正常转身的。

下面是第292帧的截图，包括 daz importer 和 DTB 两种方式导入的模型。
![daz importer frame292](https://user-images.githubusercontent.com/5558722/163919440-dbe3cb4d-c8a0-4d46-9ff2-ff0e59b5accf.jpg)

![DTB frame292](https://user-images.githubusercontent.com/5558722/163919451-22f16f3e-3f47-4c9c-88ea-e2963c396381.jpg)


这个动作数据，骨骼不是日语编码，会出现shift_jis报错。需要打开mmd，加载一个TDA模型，加载这个vmd文件，然后另存为一个新的vmd文件，这个新的vmd文件，就会自动变成日文编码，就不会报错了。

如果你使用Blender 3.1，那么Blender报错可能不会自动跳出来，只会在底部状态栏显示一个红色的警告，需要自己去点开才能看到报错信息。

再次提醒，如果没有扎实的3D基础知识，就请像其他用户一样，老老实实跟着文档、或 上面新提供的视频教程 进行操作，一步都不要改动。

**Comment by caviar-cn** [comment]
我本人本来就不是专业K图的，只是个程序员，其实一直想让您提供标准Blender保存的 G8 和MMD模型就这目的，您设置好保存好，我拿来就不用去盲人摸象的一点一点测试了，说真的实在难以理解这么多东西的细节。
其实，我是牛，你是弹琴的，希望能理解我的处境。
得到您的回复，我会在尝试一下。

**Comment by butaixianran** [comment]
你要的视频教程已经提供了，请看看教程，看哪一步和你的操作不一样。

问题不在于你不了解，其他用户也是新手，甚至不是程序员。所以，他们会老老实实按照文档、按照视频教程，一步不改的操作，就不会有问题。

**Comment by butaixianran** [comment]
这个压缩包里面是个只有一个G8默认人模的Blender 3.1的项目文件。不带有表情。

链接: [https://pan.baidu.com/s/1PrGRQSMDG9-TDpMK0n5tBw?pwd=xbc4](https://pan.baidu.com/s/1PrGRQSMDG9-TDpMK0n5tBw?pwd=xbc4)
提取码: xbc4

你看你靠这个能不能找到问题吧。

再次，再次提醒，对着文档或视频，一步不跳过、不改动的进行操作，就不会有问题。其他更加外行的新手、女孩子，老老实实对着教程，就搞定了。

**Comment by caviar-cn** [comment]
转换动作后，骨骼鬼畜抖动 （偶尔突然抖一下）怎么处理？

**Comment by caviar-cn** [comment]
使用您提供的 G8_DazImporter.blend 后，完美了。不抖了，也转身，万岁。
现在承认，是我导入G8模型的问题，实在太迷糊，但您别不信，我重复安装插件，导入G8,不下数十次了，每次都达不到效果。
感谢，您提供的 G8  Blend 文件。

**Comment by butaixianran** [comment]
原因很早就告诉过你了，解决方法也已经给你了。

要么，老老实实对着教程来。现在有视频教程，就对着视频教程一步步查错，包括选项。

要么，就正确安装DTB。因为DTB一旦安装正确，使用时就不需要设置，所以没有设置问题。

**Comment by caviar-cn** [comment]
十分感谢，
感觉可能是我计算机内安装的DAZ和Blender 版本和插件差距或者干扰导致的，
在我的计算机，自我感觉这些软件就被折腾的很混乱。：）））

**Comment by butaixianran** [comment]
反复安装没有意义，你需要检查的是安装之后的设置和操作，请对着视频教程检查设置。

你声称你是程序员，我就拿开发举例。数据库使用时碰到问题，难道重新安装数据库？数据库没有设置好，操作不正确，重新安装能解决？

这里的情况也是一样的。请检查安装之后的其他步骤。

**Comment by butaixianran** [comment]
其他用户反馈了一样的问题，是因为diff daz import的Global Setting里面，Rigging的部分，勾选了很多限制旋转的选项。把这些选项全部去掉勾选之后，就正常了。

![rigging](https://user-images.githubusercontent.com/5558722/188907591-a62fa938-6e7f-4c77-8c56-178cf07907ca.jpg)


这个内容，已经更新到github中文文档底部的“常见问题”中，你可以查看。
