### ISSUE TITLE
手臂旋转不完全一致问题

### ISSUE THREAD

**Issue by yleo999** [butaixianran/Blender-Vmd-Retargeting#13]

**Comment by yleo999** [comment]
补充一下  导入的设置  版本1.6.1


![2022-05-01_104100](https://user-images.githubusercontent.com/102129949/166129938-96568327-e95f-4e7b-80e7-06ef6039e634.png)
![2022-05-01_104142](https://user-images.githubusercontent.com/102129949/166129944-e2434f46-4c5c-4670-a08a-dee929528fda.png)

**Comment by butaixianran** [comment]
Daz模型手臂长度，身体厚度，比例都和mmd模型不同，因此旋转一样的角度，手掌到达的位置也会不同，所以才需要手臂旋转比例这个东西。

这个无法根治，比较好的选择是，通过调整旋转比例，宁可不到位，也不要穿模。尤其是衣服要有物理碰撞的时候。

手臂中间弯曲，是因为导入的vmd动作，使用了扭曲骨骼。这种twist骨骼，基本上就只有Natsumi San这一个vmd作者在用。

daz扭曲骨骼的机制和mmd的扭曲骨骼有根本差异。他的设计目的，是用来放松变形过头的皮肤，不太适合用于身体运动。

因此，如果vmd动作作者，把扭曲骨骼拿来做跳舞动作，那么，转换到Daz，就注定会导致手臂在中间有一点弯曲。

好在大部分情况非常不明显，万一觉得有点明显，可以穿件有袖子的衣服解决

**Comment by butaixianran** [comment]
顺便一提，如果接受少量穿模，希望手掌更加到位，可以把上臂旋转比例改为1.0，下臂依然保持0.8

**Comment by yleo999** [comment]
懂了 多谢

**Comment by butaixianran** [comment]
重新启用该issue，作为常见问题放在这，提供给其他用户参考
