### ISSUE TITLE
CC3模型导入Vmd动画后，下半身动作异常

### ISSUE THREAD

**Issue by frankin5** [butaixianran/Blender-Vmd-Retargeting#14]
Blender：3.0.0
Plugin: 1.6.4
Model: cc3官方APose模型

case1:关闭Body IK选项，下半身动画不正常
![image](https://user-images.githubusercontent.com/3905968/168613730-0a7e4125-d11e-4dea-a012-5d921c61b041.png)
case2:打开Body Ik，导入动画后骨骼扭曲
![image](https://user-images.githubusercontent.com/3905968/168614763-eda16157-0a99-4313-81f3-405105094234.png)

导入的配置项：
![image](https://user-images.githubusercontent.com/3905968/168614988-35642420-a187-4743-a07f-9087cf28833a.png)

使用Daz模型也有一样的问题。

求助

**Comment by frankin5** [comment]
找到原因了，是因为我的单位设置缩放比例为 0.01 调整为 1 以后就好了。

set unit scale = 1

**Comment by butaixianran** [comment]
从截图看，可能其他用户也存在自行修改Blender单位的问题，感谢反馈。已经在文档的常见问题中，添加检查单位的checklist。

**Comment by frankin5** [comment]
> 从截图看，可能其他用户也存在自行修改Blender单位的问题，感谢反馈。已经在文档的常见问题中，添加检查单位的checklist。

有一个额外的问题想咨询下，Blender里将Action动画Bake合成以后会出现腿部动画漂移，看了下应该是 Vmd Ik 这个轨道没有被正确烘焙，不知道你是否有解决方案？ 或者将轨道动画合并导出有其它更好的实践流程？

![image](https://user-images.githubusercontent.com/3905968/168872838-b9767a4e-71e5-4a69-b571-44656063cd2c.png)

**Comment by butaixianran** [comment]
我这边bake一切正常，daz和cc3都正常，什么问题都没有。请检查你的bake选项，是不是勾选了什么不该勾选的设置。从截图看，像是勾选了“清除约束”。IK也是一种约束，如果bake时勾选去除约束，Ik自然就不会bake。

如果是想把IK bake成FK，请搜索相关教程。

**Comment by frankin5** [comment]
> 我这边bake一切正常，daz和cc3都正常，什么问题都没有。请检查你的bake选项，是不是勾选了什么不该勾选的设置。从截图看，像是勾选了“清除约束”。IK也是一种约束，如果bake时勾选去除约束，Ik自然就不会bake。
> 
> 如果是想把IK bake成FK，请搜索相关教程。

THx
