### ISSUE TITLE
导入vmd 到 Bkebder 是 30帧，用什么方法能导入成60帧呢？

### ISSUE THREAD

**Issue by caviar-cn** [butaixianran/Blender-Vmd-Retargeting#15]
导入vmd 到 Bkebder 是 30帧，用什么方法能导入成60帧呢？

**Comment by butaixianran** [comment]
导入动作的时候，虽然是把项目设置为30帧，但是，实际上导入的数据，是按照vmd文件中提供的帧数来的，并不在乎blender项目设置的fps。  

也就是说，你使用的vmd动作，是基于60帧制作的吗？  
* 如果是，只需要导入后，再改项目为60帧即可。
* 如果不是，那么这个vmd文件不具备60帧的数据，你改为60帧，也只是相当于快放而已。

一个技巧是，导入后的动作，成为了NLA上的一个个clip剪辑块，因此应该可以调整速度。所以，可以把项目改为60帧之后，修改clip的速度，把30帧的动画变成60帧。详情请自行搜索：“blender Frame rate conversion” 以及 "blender Time Remapping"自行学习。

**Comment by caviar-cn** [comment]
收到，学习中，感谢
