### ISSUE TITLE
如何将 CC4 模型导入 vmd 动作后的 IK 骨骼放到原 root 骨骼下？

### ISSUE THREAD

**Issue by Sefeng** [butaixianran/Blender-Vmd-Retargeting#17]
**Blender version:**  3.0.0

**Model type:**  CC4  

**Issue:**  模型 动作导入之后， 效果完美， 导出 fbx 文件导入 ue5 时提示 ”多个根骨骼， 无法导入“。 vmd 动作导入 CC4 模型后， 原根骨骼同级新增了 mmd_ik_l 和 mmd_ik_r 两个根骨骼， 求教如何处理？

daz 模型导入 vmd 之后没有问题， 两个 ik 骨骼是附属在原 root 骨骼下； 尝试了将 CC4 新增 ik 骨骼移动至 root 骨骼下， 动作错乱。

**Comment by Sefeng** [comment]
https://www.youtube.com/watch?v=z58QHe1yUzA

**Comment by butaixianran** [comment]
这个你可以很简单的搜索“unreal import fbx multiple root bones”找到大量的答案。

解决方法都一样，blender中，在编辑模式，选择mmd_ik骨骼和root骨骼后，按ctrl+P设置 mmd_ik骨骼 和 CC_Base_BoneRoot 骨骼的父子关系，设置的时候，选择keep offset.

如果有额外问题，可以先搜索“unreal import fbx multiple root bones”，有大量重复的、详细的描述，包括视频。

你提供的youtube视频，通过修改模型名称为root，来制造一个新的root。但CC人模下，已经有CC_Base_BoneRoot 这个骨骼了，其中包含了root单词，因此修改模型名称是没用的。

**Comment by Sefeng** [comment]
感谢回复！ blender  中 keep offset 设置父子关系后成功导入ue5。 blender 导入 ue5 的模型骨骼 和 通过 CC4 导入 ue5 的模型骨骼不一致，  CC4 导入 ue5 的模型通过官方插件（auto setup for unreal）设置后， 模型效果较好 ， 想使用 blender 导入的模型动作， 还需要 骨骼重定向， 手动设置重定向效果不佳。

求教： blender 导入动作后的模型和动作 如何导入 CC4 ?  想在 ue5 中 CC4 模型使用动作， 是否有其他的实现思路？

**Comment by butaixianran** [comment]
cc4是个捏人软件，动画大概是导不过去的，要导回，应该是导回到iclone。

blender人模导入ue5如何设置，是非常基础的知识，还请网络搜索自学。

ue那边，或许也有 blender to ue的插件可以用。比如可以直接读取.blender文件的插件之类的。这个请自行搜索。

如果没有插件，一个折中的办法是，使用gltf 2.0格式导出，而不是fbx格式。

gltf 2.0的导入导出方面，也请自行学习。

blender对导出fbx有很多限制，比如，不允许有自定义shader，不然材质就不导出。

因此，你的cc to blender扩展面板上，要先替换shader为标准shader。

导出方面，不是本扩展的服务范围，而是blender本身的基础使用知识，还请自学。

**Comment by Sefeng** [comment]
感谢指点， blender 导入 ue 后， 替换了 auto setup 插件生成的模型材质基本达到预期效果。
