### ISSUE TITLE
腿总是不直。弯着腰的感觉

### ISSUE THREAD

**Issue by lancelot1977** [butaixianran/Blender-Vmd-Retargeting#18]
不知道是否是身高不匹配的问题？总感觉动作很憋屈。 在mmd上没问题。

如图

![this is image](https://preview.redd.it/qxrca62bw4q91.png?width=1888&format=png&auto=webp&s=d64c294bfbf64a25a064b779e24e986c4e368598)

**Comment by butaixianran** [comment]
有可能，请问是使用的哪个vmd动作，我们这边也试试看。如果这个问题比较常触发，我们可以开发个设置来缓解。请先提供vmd动作名称，让我们可以测试。

**Comment by butaixianran** [comment]
我这边测试下来，是穿高跟鞋 + IK 才会感觉比较明显的现象。高跟鞋抬高了腿长，IK限制了脚不能穿入地下。

解决方法2个：
* 不穿高跟鞋
* 或者，从mmd模型身上，转换动作到Daz人模上。这样就不会创建IK。
