### ISSUE TITLE
VMDRetarrgeted in Blender, Exporting As FBX for Unity at default 30 fps doesn't work

### ISSUE THREAD

**Issue by galacticePZ2** [butaixianran/Blender-Vmd-Retargeting#19]
Exporting at default 30 frames per second in Unity. Unity will tell me that frames per seconds is 0 and that it will change it to 1. And then it doesn't get the full frames of the animation . For example a 6000 frame dance animation MMD, will only get 240 frames. The only way to get the full dance is to change the frames per second to 60fps.
But that's not the real original fps of the MMD motion, and i don't think there's a way to change back the fps in Unity.

Do you have some tutorial on how to export from Blender to Unity after using VMD Retargetting?

**Comment by butaixianran** [comment]
Have you baked your motion before exporting? Do you know how to bake animation?

**Comment by galacticePZ2** [comment]
Thanks, no i didn't bake my motion. I don't know much about Blender. I just wanted to use your product to first fix them so i can take them and use the animations in Unity.  I watched a video today about how to bake animation. it says press B, and then select the animated object( they show a cube but i'm guessing i select the character in my case). And the it says Go to Object/ Animation/Bake.

And in that following window you choose Bake data Pose or Object. I'm guessing i choose Object, but i'm not sure. Then press ok, and it places every keyframe in the frames. And then it says to export the selected Object that contains the Animation( In the hierarchy) so that would be the Daz character...and go to the Menu and choose export to FBX.
Is that how you do it?

But then i'm also unsure the FBX export options, this is what i did before and in Unity it would have the character facing the wrong direction
1. Limit to Selectede Object
2. Object types: Only Amature and Mesh
3. Forward  :  -ZForward
4. check Apply Unit, Use Space Transf
5. check Bake Animation with the following checked
&Key all Bones &NLA Strips &All Actions &Force Start/End Key.....
6. Under Geometry only have this box checked: Apply Modifiers
7. Under Armature only have this box checked: Add Leaf bones

Is Any of that wrong? Im' sure they are wrong
if you have time to respond you can.

**Comment by butaixianran** [comment]
ok, you bake it with wrong option. You only baked object's motion, not bone's motion.

There is no motion on object level. All motion is on bones. You must bake Pose data, not object, to bake bone's motion.

Our youtube channel's latest video is a tutorial about how to bake animation. Check that video. 

It is about how to export animation to Daz. But the bake part is the same. Follow that tutorial, do the same thing to bake.

That video's link is also in this project document's **Blender Tutorial** part.

[https://youtu.be/FEA9hVouKFg](https://youtu.be/FEA9hVouKFg)

once you baked animation, you do not need to bake it again when exporting fbx.

And next time you searching for tutorial, search character tutorial, not object.

**Comment by galacticePZ2** [comment]
Hi Thanks I followed your tutorial. it helps and i was baking and waiting and waiting..6400 frames motion because all my motions are dance motions and the motions are dances of full songs ( from 2:30 minutes to 4plus minutes) so they will all be long like this. ANd in your video it said if they're more than 3000 it may crash and i think it crashed because i was waiting for 10 minutes and still not done. So i think your plugin will not work for me sorry.  too bad.

**Comment by butaixianran** [comment]
Hi, in that video I made it very clear, Daz may crash, not blender.
And bake is slow, a 6400 frames motion, you need to wait hours.

This addon and blender all works fine, just you choose not wait for baking.

**Comment by galacticePZ2** [comment]
oh ok. i'll wait. hours means 8 hours? i hope it's just 1 hour
