### ISSUE TITLE
tested genesis 8.1 

### ISSUE THREAD

**Issue by Bolsdip** [butaixianran/Blender-Vmd-Retargeting#2]
The model doesn't turn around. All other motions seem to work.

Is there a way to keep the motion and continue cleaning up when converting the rig to rigify?

**Comment by butaixianran** [comment]
hi, I'm not sure what you are asking.

Case 1: You mean, your model doesn't turn around when using a G8.1 model?

Case 2: Or, you mean, your G8.1 model works fine, but doesn't turn around after converting to rigify?

Which case are you talking about?

For case 1, that's a problem. I need you offer a vmd file at least a few key frames to test. Or tell us the vmd motion's name so we can try to get it.

For case 2, that is not actually a problem with this addon. You need to ask what the diffeomorphic daz importer does when converting rig to rigify.

But for case 2, you can always try to retarget motion from a mmd model. In that way, your Daz model won't need IK bones. So you have the best chance to make it work even after converting it into rigify.

There is a video tutorial about how to retarget motion from a mmd model:
https://www.youtube.com/watch?v=rttA3v_5S2I

**Comment by Bolsdip** [comment]
hi, thank you. it's for case 1, I tried a lot of motions, they all have some problem with not turning around and/or feet staying in one area (using IK instead of FK). I'm using select vmd file button method 

if there's going to be an update for this retarget to work with rigify additionally, it would be great. It's difficult to work with the default rig.

**Comment by butaixianran** [comment]
Hi, that doesn't sound right. We test a lot of motions, there is no case Daz model won't turning around. 

There is no way it won't work on a lot of motions. Could you offer a name of the vmd file you tested or a single pose of your vmd file for us to test it?

If you don't want to offer a vmd file or a pose file, you can also upload a short video about how you import and convert the motion, so we can see which part get wrong.

Also there is a version 1.1.1 in blender market and we updated the IK part in document, you can check it.

**Comment by butaixianran** [comment]
Hi, a good news for you.
Another client has the same problem as you are, and offered the vmd file for us to test. So we found the problem.

This kind of vmd files are using Center Bone for rotation. But center bone is designed only to use as an additional layer for moving location, so we didn't handle its rotation. Vmd motion's author should not use center bone in that way.


I'll handle it then release a new version. I'll inform you after it released. It may take 1~2 days.

**Comment by butaixianran** [comment]
Hi, we fixed some bugs reported by other clients, which is very similar to yours.

With latest version 1.1.4, I believe your issue has also been fixed. 

Try the latest version, and thanks for your report
