### ISSUE TITLE
I need to convert body, eyeball, facial, viseme for my model

### ISSUE THREAD

**Issue by SlimeVRX** [butaixianran/Blender-Vmd-Retargeting#20]
**Model type:**  Maya/FBX

**Issue:**  Is there any way to convert Body, Eyeball, Facial, Viseme from MMD Model to My Model.
I'm not sure your plugin can convert Eyeball, Facial, Viseme for any model so I want your advice.

**Screenshort:**

![image](https://user-images.githubusercontent.com/99313947/203967420-0b983d89-2ec2-4b72-a33f-857bdbcda559.png)

**Video:** [Link](https://drive.google.com/file/d/1URRhROowrWW_7tNz4bhjjsBkbtnDsQL8/view?usp=sharing)

Thank you very much!

**Comment by SlimeVRX** [comment]
Goal: Convert Body, Eyeball, Facial, Viseme from MMD Model to My Model
- The first way: Use your plugin
- Second way: Convert my model to MMD format

I will pay you a fee if you can help me. Thanks a lot!

**Comment by butaixianran** [comment]
Hi, we only offer service for our addon. This is out of our service range.

Since it is your own model, which is not based on Daz or CC standard, you have to learn how to convert shape keys and shape key drivers by yourself.

**Comment by SlimeVRX** [comment]
Hi, Thanks for the quick response!

Currently, I can't find any tool that can help convert Eyeball, Facial, Viseme from MMD Model other than your plugin. Please add Wechat friends with me.

Thank you very much!

**Comment by butaixianran** [comment]
Hi, there is no addon for that or your model. You have to learn how to map one shape key to another, or write your own script.

I don't offer service to teach those. You need to google it and learn those from internet by yourself.

**Comment by SlimeVRX** [comment]
Yes, thank you! 

Since you are the first to do it, my work goal is completely possible, I will try.
