### ISSUE TITLE
foot ik not worked well with CC3 character

### ISSUE THREAD

**Issue by xoyojank** [butaixianran/Blender-Vmd-Retargeting#21]
knees are not bent correctly
![image](https://user-images.githubusercontent.com/2873643/208230118-8aa7de06-6d15-438b-a90a-2c27182b3402.png)

**Comment by butaixianran** [comment]
There is no such issue in our test. Which vmd motion are you using here?

Also, are you retargeting motion from this mmd model, or import motion to CC character directly?

**Comment by butaixianran** [comment]
ok, we test it again, with latest cc blender tool. Seems our new ik limit setting does not work well with CC3. It seems an issue hiding in CC3, not an issue of our addon.

You better use CC4, which has no such issue.

We'll try to target this CC3 issue and fix it in next version. we'll let you know when it's done.

**Comment by butaixianran** [comment]
ok, we find cc3 model's issue, and add a quick fix to that model. Update your addon version to latest ver1.19.1 to get the fix.

You need to re-open blender after re-installing an addon.
