### ISSUE TITLE
import with MMD failed

### ISSUE THREAD

**Issue by xoyojank** [butaixianran/Blender-Vmd-Retargeting#22]
![image](https://user-images.githubusercontent.com/2873643/208231686-3bf9a7a9-dc03-45b7-9bbe-3042fd6df778.png)
it seems there is a bone not found in MEIKO model

**Comment by butaixianran** [comment]
MMD's default Meiko model is too old and lack some common bones.

If you want to retarget motion from a mmd model, **use a TDA model**. That is the bone structure we used in this add-on.

Also, uncheck "**rename bone**" when importing mmd model into blender. We use its japanese bone name for bone mapping. As our video tutorial mentioned.
