### ISSUE TITLE
The character is suspended, not touching the ground

### ISSUE THREAD

**Issue by SlimeVRX** [butaixianran/Blender-Vmd-Retargeting#23]
Thank you so much for creating this amazing plugin!

**Blender version:**  
- Blender 3.3 LTS

**Plugin Blender version:**  
- VMD Retargeting 1.19.1
- DAZ Importer 1.6.1.0824

**Model type:**  
- Daz Studio 4.21 Pro

**Issue:**  

The character is suspended, not touching the ground

**Offer at least one of following for testing:**  
- Video: https://youtu.be/ugvaMzIQul4
- File (Vmd + Blender): https://drive.google.com/file/d/1EaHOwA3qna7KCljzAssL8xnjyQYBo2Oz/view?usp=sharing

**Comment by butaixianran** [comment]
As your video shows, you set IK to off. Then it won't touch ground. 

For those vmd motions don't use IK, there are 2 solutions to make it works better. These 2 solutions are already in product document.  Check the common issues: [Leg won't bend](https://github.com/butaixianran/Blender-Vmd-Retargeting#leg-wont-bend) part.

**Comment by SlimeVRX** [comment]
Thanks, I will try again according to your instructions.

**Comment by SlimeVRX** [comment]
Hi @butaixianran 

I downloaded a blender file you shared. I was really surprised at the results that were superior to what I did on my own.

Can you share the software versions you are using? 
Daz Studio Version? Blender Version? VMD Retargeting Version? DAZ Importer Version?

These are the versions I'm using: 
Daz Studio 4.21 Pro, Blender 3.3 LTS, VMD Retargeting 1.19.1, DAZ Importer 1.6.1.0824

I want to reproduce your results. Do you have any advice for me?

VMD Retarget results using your Blender file: https://youtu.be/LJDrSyKL3kI

Can you share the Blender file that can retarget the mouth and eyes? And DAZ Studio .duf file 

Thank you very much!

**Comment by butaixianran** [comment]
I use the exactly same version as yours.

Your video just shows a normal importing result. Legs are ok because this vmd motion uses IK. 

If your own model can not get the same result with the same vmd motion. You need to config your daz importer addon.

In vmd retargeting addon's document, check everything in common issue section one by one, to make sure you set everything right.

For example, you may have checked rotation limit in daz importer addon's global setting. Which is no good for mmd motion. So you need to uncheck them.

**Comment by SlimeVRX** [comment]
Thank you, I will try again.

**Comment by SlimeVRX** [comment]
Hi @butaixianran 

Vmd Retargeting worked perfectly when I switched from Blender 3.3 LTS to Blender 3.1

I'm having another problem while exporting MMD motion to Daz Studio. I created a new [issue](https://github.com/butaixianran/Blender-Vmd-Retargeting/issues/24). Please help me!

Thank you very much!
