### ISSUE TITLE
Comparison between DAZ3D and CC4 model

### ISSUE THREAD

**Issue by SlimeVRX** [butaixianran/Blender-Vmd-Retargeting#25]
**Blender version:**  
- Blender 3.1

**Plugin Blender version:**  
- VMD Retargeting 1.19.1
- DAZ Importer 1.6.1.0824
- CC/iC Pipeline 1.5.2

**Model type:**  
- Daz Studio 4.21 Pro
- Character Creator 4 v4.12

**Issue:**

In the position of the rotator, CC4 is not handled well, and the skin at the rotator is deformed

**Offer at least one of following for testing:**  

CC4:
![image](https://user-images.githubusercontent.com/99313947/209081553-124c94d2-14cc-4932-9344-406168563ea5.png)

DAZ3D:
![image](https://user-images.githubusercontent.com/99313947/209081603-53c9ea15-4478-4aba-962a-787a074faea4.png)

Video:  [Link Video](https://youtu.be/z_SoKT2O4jA)
File: [Link File](https://drive.google.com/file/d/1_K8TY40c_WRrPyjj2gr_Jv-KpMYU-jrs/view?usp=sharing)
- Daz3D Studio [.duf] + Blender
- CC4 [FBX] +Blender
- VMD

**Comment by butaixianran** [comment]
We only answer questions about our addon. This motion is converted correctly, so it is not an issue of vmd retargeting addon. You can ask that in CC's official forum, or in cc blender tool's github repo.

**Comment by SlimeVRX** [comment]
Yes, I will find out. Thank you for making this awesome plugin!
