### ISSUE TITLE
[Reopen] Incorrect motion when exporting to Daz Studio

### ISSUE THREAD

**Issue by SlimeVRX** [butaixianran/Blender-Vmd-Retargeting#26]
I was helped by @butaixianran to solve this problem, see details at: https://github.com/butaixianran/Blender-Vmd-Retargeting/issues/24

I will write a tutorial on how to solve the problem

**Comment by SlimeVRX** [comment]
I don't remember exactly which method I used but in my note there are these 2 instructions:
- https://renderguide.com/daz3d-how-to-hide-scene-parts-that-are-not-selectable/
- https://www.daz3d.com/forums/discussion/301786/hide-multiple-items

**Comment by SlimeVRX** [comment]
![image](https://user-images.githubusercontent.com/99313947/210290709-babc185c-fc89-4d55-85ec-71de50e3f1fc.png)

Note: Look for "Show Hidden ..." and enable all options that have it

**Comment by butaixianran** [comment]
Do not open new topic for the same issue. The old issue is already a tutorial. No need open a new one to do the same thing.

If you do not have an issue, do not open a topic.

**Comment by SlimeVRX** [comment]
Yes, I understand, I will delete this issues

**Comment by SlimeVRX** [comment]
I have added the tutorial to the old Issues. Please delete this issues

Thank you very much!
