### ISSUE TITLE
Loading Pose I saved from one of VMD frame, but when I load the pose after convert the rig into rigify/mhx, the ik is broken, just rotating like FK system

### ISSUE THREAD

**Issue by benagastov** [butaixianran/Blender-Vmd-Retargeting#27]
**Blender version:**  
make sure you use 3.0+ before open an issue

**Model type:**  Daz Genesis 8

**Issue:**  
I use Dollarless motion capture for getting pose I want for drawing reference. After convert the BVH with DSSc and LiveAnimation, I can manage to import it to Blender. Loading Pose I saved from one of VMD frame, but when I load the pose after convert the rig into rigify/mhx, the ik is broken, just rotating like FK system. It is supposedly move the hand and the arm, but I only can rotate the arm. Moving and rotating are different things.

**Comment by butaixianran** [comment]
rigify/mhx is not supported.
To import mmd motion onto Daz model, addon has to add 6 IK bones onto your Daz model. So, it's not a daz model anymore.

But you can load a second Daz model, then use any free retargeting addon, to retarget motion from first one to second one. In this way, it won't need the IK, so you got your motion onto other Model type.

**Comment by benagastov** [comment]
Thank you for your response, I can import the pose that I want to Daz Studio, but is there any way to use IK while I am still using the same pose? I need IK to tweak the clumsy poses easily. Ik made my character more flexible and looks elastic

**Comment by butaixianran** [comment]
Daz has a tool can pin to character's body to simulate IK. Search that. 

But if your model already has motion on body, then pin tool will stop character's hands and feet from moving. Since they are controlled by IK pin tool now.

You should finish all your adjusting tasks in blender, before exporting to Daz. Daz is not a good tool for animation.
