### ISSUE TITLE
retarget doesn't work with CC3 character 

### ISSUE THREAD

**Issue by yankyankyank** [butaixianran/Blender-Vmd-Retargeting#4]
hello there,

first of all - thank you for your hard work and providing this amazing tool. 
im facing a problem with my CC3 character, i recorded the whole process so you can have a precise idea of my problem, as you can see, after importing my fbx from CC (i used the CC3 plugin in blender) the retarget doesn't work... am i missing something? 

https://user-images.githubusercontent.com/72126935/155858983-687bec81-c972-4586-a40a-e9abb34c0242.mp4

many thanks for your help,
best

**Comment by butaixianran** [comment]
hi, there are 2 things I noticed in your video.

#### That error says: IK does not have attribute as "enabled". So, you must use a blender version this addon can not work.

This addon is created and tested in Blender 3.0. There is feedback told me it can be used in 2.9x. But officially, it request blender 3.0 to work.

Also make sure you are using the latest version of this addon, which is 1.2.0  


#### Another thing is: your cc3 model's default pose is very different from ours.
Following is the rest pose of my cc3:  
![](https://raw.githubusercontent.com/butaixianran/lib-links/master/img/cc3_def.jpg)

Did you export your CC3 model from iClone? In that case it is not tested. We only use Character Creator  

We actually uses CC3+ model. So, you need to convert you cc3 into CC3+ model in Character Creator. (Which is default)  

There is an official tutorial for this, just click 1 button:  
[https://manual.reallusion.com/Character_Creator_3/ENU/3/Content/Character_Creator_3/3.3/05_Character/Converting-CC3-to-CC3-Plus.htm](https://manual.reallusion.com/Character_Creator_3/ENU/3/Content/Character_Creator_3/3.3/05_Character/Converting-CC3-to-CC3-Plus.htm)  


And when you export your model from CC, make sure you using following settings:  
* Target software is blender
* No animation
* Default pose is A pose  
![](https://raw.githubusercontent.com/butaixianran/lib-links/master/img/cc3_export_setting.jpg)



**By the way, when using CC3 model, you may want to set Arm rotation rate to 1.0.(Default is 0.8 for Daz model)**
