### ISSUE TITLE
Feet and leg was not working well

### ISSUE THREAD

**Issue by gumi0911** [butaixianran/Blender-Vmd-Retargeting#5]
**Blender version:**  3.1
make sure you use 3.0+ before open an issue

**Model type:**   CC3  

**Issue:**  Really appreciate about this addon and it help me a lot.
Sorry since I am not a Blender expert and I am not very familer with it and my question may seems dum. But I follow all the instruction and import both the model and the motion but all the leg motion was not working well and I have try using differernt motion but still have the same issue. is that any way to slove it? Here's the video about that. 

Video:  

https://user-images.githubusercontent.com/101471414/158027561-1abfd01d-a256-467e-a4e3-85d64989f1b7.mp4

Thanks a lot

**Comment by gumi0911** [comment]
Also, I got this when I execute the model
![image](https://user-images.githubusercontent.com/101471414/158028255-c9385404-1e90-4833-a313-da49d1fd83c3.png)

**Comment by butaixianran** [comment]
hi, thanks for your report. looks like there is something changed in Blender 3.1. This addon is developed with Blender 3.0.

I'll try to fix it today, and release a new version for it.

**Comment by butaixianran** [comment]
ok, we fixed it, and uploaded a new version 1.4.1.
Now it should work on Blender 3.1

Also, If you are using CC3 model, you better set arm rotation rate to 1.0. Default is 0.8, which is for Daz model.

**Comment by butaixianran** [comment]
Also, we updated a version 1.5.0 to support twist bones. Check the latest version.

**Comment by gumi0911** [comment]
Thank a lot for you work!!!!! It now work perfectly!!

**Comment by butaixianran** [comment]
Done
