### ISSUE TITLE
眼球 表情 口型 动作无法转换，我尝试很久把 Blender 内的 G8动作导入 DAZ 里，没能实现，您是否可以提供一个方法

### ISSUE THREAD

**Issue by caviar-cn** [butaixianran/Blender-Vmd-Retargeting#6]
![image](https://user-images.githubusercontent.com/101509220/158060944-3192c8f9-9718-463e-b868-b27c16f2809a.png)
眼球 表情 口型 动作无法转换，我尝试很久把 Blender 内的 G8动作导入 DAZ 里，没能实现，您是否可以提供一个方法

**Comment by butaixianran** [comment]
hi, 你的意思是，把表情口型从blender导出，导入到Daz吗，这个确实是无法转换的。

表情口型，不是操作面部骨骼，而是操作morph。在blender中，是操作shape key 的driver。driver这个东西，是blender独有的，没有能够导出的方式。

即使是shape key，Daz也是不能导入的。你要知道，Daz的导入功能超级弱。除了bvh和obj，几乎其他任何东西都难以导入。

很遗憾，这个部分无法实现。

身体动作应该是可以通过导出bvh，再把bvh导入Daz实现的。

**Comment by caviar-cn** [comment]
![image](https://user-images.githubusercontent.com/101509220/158089518-31229eab-2ef7-49f8-81fd-b3bd827f72c7.png)
身体动作导出bvh后，导入daz会变形严重，您是否可以做个视频来演示导出过程呢？
还有您是否可以吧MMD模型VMD动作文件 DAZ G8的模型也一并共享一份呢，因为版本问题，在模仿和调试的时候总有差距。
十分感谢

**Comment by butaixianran** [comment]
这个，blender的座标轴方向，和daz是不一样的，我还没有试过blender的bvh导出，因为blender的导出功能，除了gltf格式，其他都做得稀烂。

mmd模型，就是标准的TDA miku模型，无修改版本，只是做视频的时候，隐藏了辫子。Daz G8就是标准的Daz G8，无修改。不存在版本问题。

我试试看再来回复你吧

**Comment by caviar-cn** [comment]
期待您的回复，我尝试吧MMD动作导入DAZ来丰富内容有一个月了，一直没完美实现，很苦恼
您是巨人的肩膀。能借力您的技术感到很荣幸。

**Comment by butaixianran** [comment]
hi, 我测试下来是不行的，必须要写程序进行转换才行。但是有个视频教程，说是可以，你可以试试看：
https://www.youtube.com/watch?v=_IV67QcCPQ8

**Comment by caviar-cn** [comment]
这个视频我有看过也做成功了，只是通过您的插件转换的mmd动作无法正常转入到daz里面。:(

**Comment by butaixianran** [comment]
你按照他的视频教程，应该会导入一个fbx模型，到blender对吧。

直接用这个扩展，把身体的vmd动作，转换到这个通过fbx文件导入的模型上试试看。因为身体骨骼结构是一样的，所以应该能成功。

然后再继续按照它的教程，把这个模型的动作，导入bvh试试看。

另外，Daz是没有脚上的IK骨骼的，所以你需要一个不使用IK骨骼的vmd动作数据。比如，广寒宫的动作：
https://www.bilibili.com/video/BV1Sz4y197i3/
(导入没有IK的动作时，在本扩展面板上，不要勾选IK，然后把位置比例X，改为0.5)

或者，从mmd模型上，转换动作到daz模型上，这样，任何动作都不需要创建IK骨骼。

反正，按照我们的测试，应该是要写程序才行的，因为不但座标系不同，正反方向不同，处理世界座标系 和 本地座标系的方式也不同。所以，这个视频教程，如果能成功转换，是很让人意外的。不能转换，才是正常的。

**Comment by butaixianran** [comment]
另一个可行的办法，我本人测试成功的，是不使用Blender，而是使用motion builder 或者 iclone的3dxchange。从而避免座标系差异问题。

先使用 pmx2fbx，把mmd 和vmd动作，一起转换为一个带动作的fbx格式的mmd模型，然后去 motion builder 或 iclone的3dxchange做模板，进行骨骼名称转换。从而把动作转换到daz模型上。

因为这两个软件，都没有座标系差异，所以导出的bvh，可以直接用于Daz。

相关教程：
https://www.daz3d.com/forums/discussion/56420/share-solution-how-to-convert-mmd-s-motion-data-into-ds#latest

**Comment by caviar-cn** [comment]
motion builder 或 iclone的3dxchange做的骨骼名称转换，模板能否共享下 ：）

**Comment by butaixianran** [comment]
这个自己做一次吧，做一次才知道怎么用。

**Comment by caviar-cn** [comment]
搞定了，谢谢大神的帮助。
