### ISSUE TITLE
Blender 导入 VMD动作数据的时候，会不带面部表情，请问怎样实现带表情导入呢?

### ISSUE THREAD

**Issue by caviar-cn** [butaixianran/Blender-Vmd-Retargeting#7]
大神:
Blender 导入 MMD的VMD动作数据的时候，会不带面部表情，请问怎样实现带表情导入呢?

**Comment by butaixianran** [comment]
github的使用说明中，有非常明确的说明，请先阅读使用说明。这个使用说明，在你下载的zip文件里面，也是有的。  

替你复制粘贴如下：  

当要导入Daz模型到blender时，你需要3个东西:  

* 合并所有骨架到人模身体骨架
* Face Unit 和 Viseme 的Morph变形
* 让所有骨骼可以调整（Make all bone poseable）

最简单的实现方法是，点击："**Easy Import Daz**"按钮  

默认，它已经帮你勾选了"Merge Rigs"。所以，**你只需勾选**："**Face Units**" 和 "**Visemes**"，然后点击导入即可。  

导入后，前往Diffeomorphic daz importer扩展的： "Finish" 部分，点击"Make All Bones Poseable"

**Comment by butaixianran** [comment]
表情，是直接从vmd文件读取，而不是从mmd模型上转换。如果你使用mmd模型转换动作，只会转换身体动作。

表情还是要从vmd文件读取。

这个在使用说明中也是有写的。请看使用说明。

我们的推荐做法是，只要没有必要，就不要从mmd模型转换动作。直接从vmd文件导入动作，是更好的选择。

**Comment by caviar-cn** [comment]
细节有点多，设置错一个就无法实现，还是想您能提供3个标准模型，提供下载就好了。
一个是 G8 的模型，一个mmd模型 ，一个vmd动作文件，
其实对于不是专业研究这几款软件的人，这些弯弯绕整明白，会掉很多头发的。
：)

**Comment by caviar-cn** [comment]
![image](https://user-images.githubusercontent.com/101509220/158511145-04550198-7922-412d-834e-9607da2b7556.png)
不选身体ik ，就会报错，选了 身体 和ik 就会要求选择 来源mmd,
选了来源mmd+面部的3个就会提示下面的图，只有不选面部只选身体和ik才能顺利执行
![image](https://user-images.githubusercontent.com/101509220/158511273-624e4436-b783-43ed-8444-c4b5428a4195.png)
头发掉一地，55555

**Comment by butaixianran** [comment]
你截图中的错误提示，不是转换出错，而是读取vmd文件中的日文骨骼或表情名称时，无法读到指定格式的日文文字。

换句话说，你这个vmd文件有问题，不符合vmd文件格式规范。

你可以在mmd中，把这个动作应用到一个Tda模型上，然后另存为一个新的vmd文件，用这个新的vmd文件试试看

**Comment by butaixianran** [comment]
你要做的事情，你提出的问题，都和模型没有关系，不存在模型版本问题。导入表情，只需要2个东西：
* 一个带表情，符合vmd文件格式标准的动作。
* 一个任意Genesis8人模，按照使用说明的方式，导入时勾选了Face Unit和Viseme.

你的出错提示显示，这不是一个正常的vmd文件，里面不包含日文编码格式的骨骼和表情名称。

根据你的截图，我去找到了"还是你的笑容最可爱"这个动作数据。和你截图的提示一样，是编码问题。只需要在mmd中，把这个动作，读取到一个TDA模型上。然后另存为一个新的vmd文件。这个新的vmd文件，就成了日文编码。就可以用了。

另外，这个动作没有使用IK，因此导入身体动作的时候，你也需要去掉勾选IK。觉得脚下有点滑步的话，去掉勾选IK之后，会出现一个"位置比例 X"的选项，设为0.5可以缓解滑步

**Comment by caviar-cn** [comment]
成功了，万岁！
还有一个小问题，我开一个新帖子咨询。
