### ISSUE TITLE
G8模型和 MMD模型尺寸有点差异，动作转换后，脚的位置飘的厉害，怎样解决

### ISSUE THREAD

**Issue by caviar-cn** [butaixianran/Blender-Vmd-Retargeting#8]
![image](https://user-images.githubusercontent.com/101509220/158722642-6a4a0a47-b13b-47ee-854f-79e98e1c73ff.png)
G8模型和 MMD模型尺寸有点差异，动作转换后，脚的位置飘的厉害，怎样才能解决？

**Comment by butaixianran** [comment]
中文使用说明中有清晰的说明，你前一个issue中，以下内容已经写给你了，这里再次复制粘贴给你：

**如果某个vmd动作不使用IK，去掉勾选即可**

如果一个动作不使用IK，而你在导入时勾选了IK，那么，因为IK上没有数据，脚就不会动。因此，你导入时也需要去掉勾选IK。

**去掉勾选IK后，会出现一个"位置比例X"的选项，设为0.5可以缓解无IK时，脚下有点滑步的问题。**

**Comment by caviar-cn** [comment]
大神，IK这个我知道的
实际上，转换的时候，G8模型的脚和MMD的脚是不对应的，我以为是我的设置原因，所以问询下
如果本身转换就有误差，那就没问题了，也不能太强求。

**Comment by butaixianran** [comment]
脚下滑步的根本原因是，这个vmd动作，不是手工制作的，而是某个软件生成的。这个生成vmd的软件，会反复把人模整体倾斜，再调整hip骨骼旋转角度，把整个人物摆正。

然而，mmd的hip骨骼，和Daz的hip骨骼，位置、高度都不一样。所以，即使Daz的人模，整体旋转一样的角度，脚抵达的位置，也不一样。

如果有IK， 就不会有这种问题。然而，它也不使用IK。于是，即使数据完美转换，最终脚的位置，还是会有差异。
