### ISSUE TITLE
mmd转g8的时候，不会转身

### ISSUE THREAD

**Issue by caviar-cn** [butaixianran/Blender-Vmd-Retargeting#9]
https://www.aplaybox.com/details/motion/RA0IwvhdQmZp
这个vmd动作，在Blender转换到G8的时候，不会转身。

**Comment by butaixianran** [comment]
这个动作在我们的测试中，是可以正常转身的，一切正常，没有任何问题。测试的是：GHG_TDA MIKU.vmd 这个文件。

这个动作是有使用IK的，因此导入时，请勾上IK。

如果确认勾上IK，还是不能转身。请提供如下信息：

Blender版本。
动作导入的方式：是通过vmd文件直接导入到Daz模型，还是通过mmd模型转换动作。
导入后的效果的视频片段，或多张截图。

**Comment by caviar-cn** [comment]
Blender版本
![image](https://user-images.githubusercontent.com/101509220/159174953-b1e19291-2f2b-4628-89d3-b0e247069766.png)
我下载不到 Blender 3.0 所以是最新版的。

下面是设置
![image](https://user-images.githubusercontent.com/101509220/159174910-01531b8e-d687-4975-a2d3-edbce6313088.png)
vmd文件直接导入到Daz模型 和 通过mmd模型转换动作，这俩我都测试过的。结果一样

![image](https://user-images.githubusercontent.com/101509220/159174856-8a1f3860-60a2-4cd9-bf38-b9ec33562fb0.png)
0帧
![image](https://user-images.githubusercontent.com/101509220/159174879-0225c4e8-c7b1-4a78-89a0-f9d67b33e96e.png)
295帧
![image](https://user-images.githubusercontent.com/101509220/159174892-1f7f796d-1932-43be-80fc-b825d0efa7c0.png)
345帧
![image](https://user-images.githubusercontent.com/101509220/159174990-5755300c-658b-4bb8-9ba0-d859e29e188c.png)
790帧

除了这个模型，还有几个模型是无法转身的。
如果需要，我提供给您下载链接

本以为帖子石沉大海了，能得到回复很开心。

**Comment by butaixianran** [comment]
hi, 从截图来看，这个可能不是本扩展的数据转换问题。比较像是你的Daz模型，没有正确的从Daz中导出。  

Daz模型，是通过Diffeomorphic daz importer这个扩展实现，你需要了解它的使用方法。我们有提供中文教程：  
[https://github.com/butaixianran/Blender-Vmd-Retargeting/blob/main/diffeomorphic_daz_import_setup_tutorial.cn.md](https://github.com/butaixianran/Blender-Vmd-Retargeting/blob/main/diffeomorphic_daz_import_setup_tutorial.cn.md)  

从你的截图中看，人物骨骼的旋转轴的方向就是不对的。因此，这是在导入Daz人模时，就出了问题。  

一个常见的可能性是，在Daz中，保存人模的时候，每次都需要使用"Export to Blender"按钮，保存一个后缀 .dbz 的json文件。  

当Daz模型有重新保存，而没有重新使用"Export to Blender"按钮导出.dbz数据时，就可能出现你截图中的现象。  

请参考上面链接中的中文教程，了解如何正确使用Diffeomorphic daz importer

**Comment by caviar-cn** [comment]
反复仔细的做了三遍，问题依旧，能否发个G8 和mmd的模型文件给我 我的邮箱 890000@qq.com
感激

**Comment by butaixianran** [comment]
再次反复强调，和模型没有关系，只要是G8就能行。

关键是，导出Daz人模时，必须有对应的.dbz文件。Diffeomorphic daz importer**需要在安装时，设置好对应的root path路径**，并在每次使用时，导出.dbz文件。

从你的截图看，不是本扩展的数据转换问题，而是Diffeomorphic daz importer这个桥接工具，没有正确的使用。

首先，在Daz中，打开一个G8人模，保持默认姿势不变，保存为一个新的项目文件。比如， testG8.duf。
然后，在菜单中，使用"Export to Blender"按钮，导出一个和项目同名的.dbz文件。 比如：testG8.dbz。放在和项目同目录下。

接着，在Blender中导入刚才的.duf项目文件。这里提供了导入Daz人模时的设置截图，请看看你的设置是否有差异。尤其是红色框住的部分。
![](https://raw.githubusercontent.com/butaixianran/Blender-Vmd-Retargeting/main/img/Daz_import_setting.jpg)


另外，请确定你的Diffeomorphic daz importer安装的是1.6.1版本，而不是1.5版本。

另外，如果你使用的不是官方Daz Studio，而是国内的什么4.12汉化版，也请告知。我们都是按照官方版本测试的，国内私人打包的Daz版本，是否会有问题，这个我们是不知道的。

**Comment by butaixianran** [comment]
如果实在搞不定Diffeomorphic daz importer，这里提供一个新的选择： 

我们上传了一个新版本ver1.6.0。这个版本，支持使用Daz官方桥接插件导入的Daz人模，而不需要Diffeomorphic daz importer。 

Daz官方桥接插件的特点是，安装麻烦，但使用简单。一旦安装好，就不会有什么导入导出时设置不对的问题，因为导入导出时不需要设置。

下面是官方Daz to Blender桥接插件的最新更新版本，支持Blender 3.x。
[https://github.com/butaixianran/DazToBlender](https://github.com/butaixianran/DazToBlender)


安装需要有一定的英文阅读能力，一般我们是不推荐的，只有实在搞不定Diffeomorphic daz importer，再尝试这个选择。

中文说明我们也更新了：
[https://github.com/butaixianran/Blender-Vmd-Retargeting/blob/main/Readme.cn.md](https://github.com/butaixianran/Blender-Vmd-Retargeting/blob/main/Readme.cn.md)

浏览其中的：
**准备Daz模型（使用Daz官方Blender桥接插件，以下简称DTB）**
章节即可

**Comment by caviar-cn** [comment]
![image](https://user-images.githubusercontent.com/101509220/159437063-0ecfda19-42b0-42bf-ba91-372e35c646be.png)
![image](https://user-images.githubusercontent.com/101509220/159437701-9b521662-6f9a-4346-822d-734fcd7438e5.png)
![image](https://user-images.githubusercontent.com/101509220/159442350-6f410f50-523e-429d-80e8-04906ed699b8.png)
![image](https://user-images.githubusercontent.com/101509220/159445096-33b41c38-7212-4a29-a974-af2a769d427d.png)
--------上面是我使用的daz和Blender 插件版本
合并所有骨架到人模身体骨架
Face Unit 和 Viseme 的Morph变形
让所有骨骼可以调整（Make all bone poseable）
![image](https://user-images.githubusercontent.com/101509220/159445877-b0d8d904-97ad-4464-8b28-48f3a846c794.png)
导入daz模型的时候的设置，

另外用DazToBlender也测试了，需要开x10放大比例，转换动作后现象一样。

几种方法都试验了，问题依然这样，排除模型的问题，我感觉可能是 VMD动作的问题(GHG_TDA MIKU.vmd)，因为至少有一多半 其他VMD动作可以使用的。
这个问题我不着急的，以后慢慢解决好了，在我的水平无法找到原因。

**Comment by butaixianran** [comment]
hi, 你提供的vmd我们测试过了，是好的，可以正常转换的。

另外，你提供的Daz版本号，不是你的软件版本号，而是官方文档上显示的最新版本号。你的Daz版本号，是在你打开Daz的时候，上面显示的版本号。或者，按照下面的方法查看Daz版本号：

Daz菜单->help菜单->About Daz Studio。里面显示的版本号是多少？

然后，你安装的Daz to Blender桥接插件，不是我们提供的支持Blender 3.x的版本。你安装的，是官方的老旧版本，只支持Blender 2.9x。在Blender 3.1是无法正常运行，是一定会报错的。然而，你也没有提供报错信息。

支持3.x的版本的项目池已经给你提供了：
[https://github.com/butaixianran/DazToBlender](https://github.com/butaixianran/DazToBlender)
请安装这个版本。

当前版本号是：2.23.7

**Comment by caviar-cn** [comment]
![image](https://user-images.githubusercontent.com/101509220/159451943-990f527b-20c4-423a-86b5-99438d72d0bb.png)）
daz 4.20
----->Daz to Blender桥接插件，不是我们提供的支持Blender 3.x的版本 支持3.x的版本的
这个我一会吃过饭在重新安装测试下。
：）

**Comment by caviar-cn** [comment]
![image](https://user-images.githubusercontent.com/101509220/159453241-17335e11-8d29-4e4b-a1d3-987ba7dd796f.png)
补充下 Blender 版本号  3.1.0

**Comment by butaixianran** [comment]
另外，提供对比截图的时候，你的mmd模型，导入vmd动作的时候，有个margin设置，默认是5帧，请把这个改为0，不然它会把动作往后推迟5帧。
![margin0](https://user-images.githubusercontent.com/5558722/159457746-a5985687-c37c-4668-b4e1-2294bd223c1b.jpg)


请优先测试直接从vmd文件导入，而不是从mmd模型上转换。

再次强调，这个动作是可以转换的，无须mmd模型就能完全一致。以下就是G8 的官方默认人模，用你提供的广寒宫动作数据，直接导入vmd模型，不使用mmd模型的转换对比效果：

![frame0](https://user-images.githubusercontent.com/5558722/159456639-d0c92a3f-2b8d-430e-8a35-fce63eba8dab.jpg)

![frame295](https://user-images.githubusercontent.com/5558722/159456636-453f1dd1-880f-45c7-8c05-dff4fc74297f.jpg)

![frame790](https://user-images.githubusercontent.com/5558722/159456626-d020365a-24a7-4b83-b253-a2bd083474d2.jpg)

因此，请在Diffeomorphic daz importer的设置上寻找问题所在。从你之前的截图看，就是没有读取到有效的.dbz文件的现象。

**Comment by caviar-cn** [comment]
支持3.x的版本的Daz to Blender桥接插件
![image](https://user-images.githubusercontent.com/101509220/159458546-c3033c93-1666-4ab2-82d7-eb9df548bf0f.png)
安装后，点不开面板，好难 :L

**Comment by butaixianran** [comment]
hi，这个是因为你没有正确的安装。请问你是先安装了老版本，然后把我们提供的新版本DTB的目录复制粘贴过去的吗？  

如果是这样的话，在复制粘贴过去之后，DTB目录下，有个__pycache__目录，必须要删除掉，再重新打开Blender。__pycache__这个目录里，依然是老旧的运行文件，所以才会报错。

我们推荐的方法是，彻底从Blender删除你的老旧DTB扩展，重新安装新版本，从而避免类似的新旧代码混合导致的安装冲突。

请使用正确的方法安装Blender扩展。如果选择手动复制粘贴文件，请了解这种手动方式的基本使用方法。

另外，Daz Studio一侧的脚本，也是需要更新为新版本的，虽然只影响高跟鞋。请参考DTB项目的安装说明。

**Comment by Sefeng** [comment]
Hi， 已购插件。  DAZ G8 官方模型 通过 Diffeomorphic daz importer 导入 blender （版本： 3.2.0)， retargeting 插件（1.8.0）直接导入 vmd (GHG_TDA MIKU.vmd) 文件到daz模型， 模型也出现不转身的情况。 

看了上面的情况是 DAZ 模型导出的问题， 按照上述 Diffeomorphic daz importer 教程核对后， 暂未发现问题。 插件是否有 debug 信息 查看 DAZ 模型的问题点？ 如何进一步排查？

**Comment by butaixianran** [comment]
本项目文档的底部，有常见问题列表，请先对着这个列表排查问题。

另外，请确定你尝试过不同vmd动作。

常见问题列表中，有一个需要注意的情况是，用户可能修改过blender的尺寸单位，也会导致问题。

另外，既然你使用的最新版本，那也可以试试看使用daz官方的daz to blender bridge来导入daz人模。1.8版本是支持的。

具体方法文档里也写了。

注意导入vmd动作时，选择正确的模型类型。

如果常见问题列表不能解决问题，请提供你出问题的截图，以及使用的vmd动作的名称，我们来看看是怎么回事。

**Comment by Sefeng** [comment]
感谢回复，我的问题解决了， retargeting 效果很赞！

我的问题是 blender 插件  daz importer 面板 global setting  下 Rigging 部分 插件 **默认勾选** 的配置没有调整。 参考视频教程中的配置调整后， 一切正常。
<img src="https://1.bp.blogspot.com/-v20h6v8b2BU/YSIXVZoyL1I/AAAAAAAAFWs/T6UsNDPPJ0EfUGWph1qurJlM1qHvtLIsACNcBGAsYHQ/s1211/dialog.png">
建议将 这部分配置 在教程中指出。

**Comment by butaixianran** [comment]
原来如此，感谢提供反馈，我会加入常见问题，希望能帮到其他用户

**Comment by butaixianran** [comment]
> 感谢回复，我的问题解决了， retargeting 效果很赞！
> 
> 我的问题是 blender 插件 daz importer 面板 global setting 下 Rigging 部分 插件 **默认勾选** 的配置没有调整。 参考视频教程中的配置调整后， 一切正常。建议将 这部分配置 在教程中指出。

请问一下，你安装的 diff daz importer 是什么版本？对照你提供的截图发现，你的截图中，不但勾选的选项，和我的不一样， **而且，可供勾选的选项，也比我的少一些项目。** 我使用的是最新的1.6.1版本。请问你是否下载了错误的版本？比如1.5版本之类的。

![Snipaste_2022-09-07_21-36-20](https://user-images.githubusercontent.com/5558722/188892708-51f63e13-a363-4308-aafc-b7f84cbd7a1d.jpg)

**Comment by Sefeng** [comment]
抱歉 我的截图误导了你。 comment 中我没有找到如何上传图片按钮， 上面我是粘贴了 diff daz importer 官方文档中的图片 URL (可能来自老版本的截图)， 我本地使用的是 1.6.1 版本。

**Comment by butaixianran** [comment]
ok，那么这个issue关闭了
